apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wireguard

generatorOptions:
  disableNameSuffixHash: true

resources:
  - wireguard-ns.yaml
  - wireguard-cm.yaml
  - wireguard-pv.yaml
  - wireguard-pvc.yaml
  - deployment.yaml
  - wireguard-svc.yaml

generators:
  - secret-generator.yaml
