kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wireguard-configs-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: wireguard-configs-pv
  storageClassName: ""