apiVersion: v1
kind: Secret
metadata:
    name: loki-stack-grafana
    type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:He0jA+o=,iv:2VPk5/pmajWkQfx5GT6bxrF4MFcl+eVxmOn6qk7DLvU=,tag:+DSwDOdbVI16Uwm4P2Ug3Q==,type:str]
    admin-password: ENC[AES256_GCM,data:nr8QI4yA74NEgMvFqvuikzKB9ESkWqIy+HkBB2ZSNTt0jr4VmYztRQ==,iv:Yh7NW+9uk/7lnFI78c+2/eXff+FJpW2W/xeWQ+Fkcxo=,tag:iUeTUgipIbCfc/N2n+KaZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-02T18:12:26Z"
    mac: ENC[AES256_GCM,data:ykI2Ax8IcO/oKAMblSJvGiwNqQvQSOZf7nBG5GK5vsqT9uli1AR7kDkANrZ/uLtZdiR+ASNECGMn9B7S2a02lCXEsaUDZn8tCWH32imZ7lltx7iuPzVpyJo7wE2thkIS67Be3bCMxcZ+KTLWoY6h8PSmNC1BprqbQydgcFY8uLs=,iv:3Kg2UnOoPkc1KLEGnu7x9b3TK3TcbRhyzu/S93rkGrg=,tag:jngU4bwfstg1nqfeLQ0GQQ==,type:str]
    pgp:
        - created_at: "2023-02-02T18:12:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA13jbxIEUYaBAQ//Zk2m+QtqvvKFSF60XvCg2AZicYFKetl3RJ1sleOYwUvo
            ak2Qv6y6qlVClU7dvICMjXFI1SfhqeQbZlKn4RZPBmtgFQi9UjvRp37vQBlZOlqQ
            EI8QNzs42SoiitI8yJwj4q/3HS4AcOh7MLST4eB8y5pOMPK4aJXOR361qtR1qJoE
            qpeRiOd9rw4VmozRFqCk+DWIseonCb6nuqXRywDukBpV6oi+3507bra94cvuVfhP
            GUFA8Qy0Xli+i0YoEyHdLU25ToLuvqbdwvSbttjzQr+qH9RIXr0T78d1wxSXJ7xd
            JsHl8WdTBlEOZuvKNcWgRoAvXEx6CKLdO7uksmM6MFFmuwHFUtFK1qo/VI1lFSLX
            tritcZK7u+atBEmDIWFDzF4in3ZmTi31XGwNAkLybc02EMFDqo7P2xzmgDDVgZnl
            S9mvSSB+HuVkDg//aRleJTBQT/8dd/vVUsUXzyV5DvkF02lRO0laZ9LtqK1tgY89
            ZebuDmjT63n6PmGFYiZ+AWuIgMdnLgi+v7qpW7D8qWC4BrHA72vtzff70bPTYVQQ
            9UBmNThNmXW8qQJro1aXf+VWE8546UJFyn/2giQmqb258lfaRjGNwIVQT2m/Kq7k
            +omzKDpf6n9ksiYFwTabhha+S1sxlt0ReN+tYeEgzD0bMDqmOD4yaBokEUZT2yrU
            aAEJAhDNhTax11KYmQWJgnqQnQy+PxQd7OrzSI0Tr5o8yGm7cyU4ugv7AVnQcEJY
            P5+1UvjARWErgwxzwumHKMxJrtnrGb+JRM8uKCAKANcFDqVgSF9gs8Q38q2CN0e+
            YQmMFHGQDwkC
            =QOZW
            -----END PGP MESSAGE-----
          fp: A895CF23FF129E6BA20E2871CCAE56820A470E76
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
