apiVersion: v1
kind: Secret
metadata:
    name: loki-stack-grafana
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:zrDn98C4rUo=,iv:Djfq9B5vVEl7d/A8CLmD+DJdijeoFM9hJHhLoo8KRpM=,tag:VmEnsUELIKTdGf11171dAg==,type:str]
    password: ENC[AES256_GCM,data:xTCjdV26FSM=,iv:zRV2PQR7z1jGUZ/4qiZn8tbfcjUNF4klnYAQl+lTeRs=,tag:aH4Xg2D2QQ5lpKbQxCyxeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-02T17:49:44Z"
    mac: ENC[AES256_GCM,data:Wd7NGSa/jGGywh2/oaY+TqTEQFnKla+9IP/SD6Nj+QuLSfrnoM0N/krAuwAp+LUDuaVW6q3jG8NXv9mkFeYvtILRTk1qcz1+ajoG98SKyrePGAgSQwh73A4y2mSSkGQpR2SeKm/Wxq4at1DzjME8WeywGEhjXZUeycinUfJtz3g=,iv:NCw4Ojqx5IkOznOnqI1vr7ZKJpIzUTtecDj+5p5jTbE=,tag:RTPt1WkF+cijPhjG/UkakQ==,type:str]
    pgp:
        - created_at: "2023-02-02T17:49:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA13jbxIEUYaBARAA0mRD1umAVQl1alCDpfEpqMtBt4x2r+LLtd0H2BHMZWs3
            yJhnOKS0uVH8Afkyd5O1zzbKxkYtIGPJtwCh4UQKje24p6samcMx2pBtapCEeDhk
            sPKjJH+jtE2nfs3eJa00dwDpAXS2HVsU3cPYT4ZnJwvQVhp+nE44eQUYAFa8jh3U
            HoTU3I4vUyk/Mx9HGwLu6x9oIDLzDslKbStheWp0L0DeHIhdNlZyiCd608JOizFd
            3X/qXXPB7h5FtrJmzq5JvTifDQcl21PKH3u5yGGEzU7f+WtdMHuP7HD2dkehVWTY
            9UELp7DRTbU9Do8c8EjA0E14TVWexZk7ZWGrunyQXwHdICXdiv4S6ih5RqIj6qSH
            +Jt/9aW3kXkB2MXGbIbRKBwFPxfNMSQGZOzdEWzgTjzn5uEs+nc9mnpdNg4SCiMh
            wuWX0RKt6WK0qinMGZqmym+py2ZxUIVZgV8iVgSlh31YMchfXni7Jl4wW4TVslwb
            M1SzKFC0mVmub7VICx7Su/bb7q7bFrPk2JlLXgZlDjD2XiVvM6vboxBQF2Em17Jg
            vuelpj5ExN329CRR6zEfq8Q0sPOASKdZyqCTxDS/cugR2ROZd9tnPqZBvfyIgFRT
            tYet1v8DZmvKxCPkR0E2/0/h+U8fsu6HRrvZkpUe6szHUgw1oym9ch7M19yvJETU
            aAEJAhAreH8s2WGdGzHmBQcxPLqNXrya49PegBa6qhWhItuyJ44LE4qvWoTOrPHR
            i80DJa7E1SGyER3DqsGdpb9WpWK0vcjTphYnHIoK/wQ/kZRZSffNnheF3KL89NXC
            NLEd6+qvUWnJ
            =kqq1
            -----END PGP MESSAGE-----
          fp: A895CF23FF129E6BA20E2871CCAE56820A470E76
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
