apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - grafana-pv.yaml
  - release.yaml
  - grafana-ingress.yaml

patches:
  - path: grafana-pvc-patch.yaml