apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/philgladman/home-rpi-ArgoCD-stack.git
    targetRevision: single-node-amd
    path: kustomize/nfs-driver
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
