# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-nginx
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   mountOptions:
#     - nfsvers=4.1
#   csi:
#     driver: nfs.csi.k8s.io
#     readOnly: false
#     volumeHandle: unique-volumeid  # make sure it's a unique id in the cluster
#     volumeAttributes:
#       server: 10.43.184.230
#       # server: nfs-server.default.svc.cluster.local
#       share: /
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-storage
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-nfs-example
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /var/www
          name: pvc-nginx
          subPath: nginx-vol
  volumes:
    - name: pvc-nginx
      persistentVolumeClaim:
        claimName: pvc-nginx