kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pihole-dnsmasq-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pihole-dnsmasq-pv
  storageClassName: ""