apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

# secretGenerator:
#   - name: pihole-pass
#     files:
#     - pihole-pass

resources:
  - deployment.yaml
  - pihole-cm.yaml
  - pihole-ingress.yaml
  - pihole-pv.yaml
  - pihole-pvc.yaml
  # - pihole-svc.yaml
