apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

generatorOptions:
  disableNameSuffixHash: true

resources:
  - pihole-ns.yaml
  - deployment.yaml
  - pihole-cm.yaml
  - pihole-ingress.yaml
  - pihole-pv.yaml
  - pihole-pvc.yaml
  - pihole-svc.yaml

generators:
  - secret-generator.yaml
