apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pihole-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /volumes/ssd-1/pihole-vol
