apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pihole-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: unique-volumeid  # make sure it's a unique id in the cluster
    volumeAttributes:
      server: 10.43.184.230
      # server: nfs-server.default.svc.cluster.local
      share: /pihole
