apiVersion: v1
kind: Secret
metadata:
    name: pihole-credentials
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:46VBzuF6+VwCicPA6klfSDc=,iv:QTvE7TSIQSrXL3+8UYr3ZuPMmPi97UWhAcp/FdtPCGc=,tag:P96eshvURZKKt1or8BLRkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-04T03:43:21Z"
    mac: ENC[AES256_GCM,data:lm+eAZmD5ipkzWFoUpWhjCs2CUo8pXdNdPLJIrCpd69UrxoD6llqTP4owIXdFeOyKUMbuALMD0IdG1ypqEgVCmYkM+f5FANJHTs8/YuoDlG9GhYt1QVpC86Mm7kc+OPtD/lXajeqiRn5pxP0jImZzVGNfSUGZspYL5cZfJUqex0=,iv:bqZ9/24rJIdu/8ZWyIoKKE+E4g9A2QW0WZMRTeul+bA=,tag:fFGlYmH+js9Tp/5iwHXqeA==,type:str]
    pgp:
        - created_at: "2023-02-04T03:43:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5O4Cu+lUBGNAQ/+JsbBDJpqAnTI3JQ9aZ263+w23QcexmEfed1CT0ls40cp
            2yBAb3AUnQToowPGM908pEzQnjtUcqJle7yFR49opTki5kxMnVTNzVe8XxbBYIi1
            lyaP9ayJeQTC1uNZqtp5wYQR2ILFIBdswn6f+HNBfTyqgLmaNNTkqrQ8Ppt7GiB8
            ite3SPD0RJC4hSCG+gMrgmLFH0nmmKcAQ7rdzS57BSrtX3f1lNZEhJHpkEDJ1JcY
            tvDrIRjv3N4wusW5crrUbUmxZWJBUoezmZSAYkwunnSoFR0OOSO1qw+h8GTQY62O
            LIhj+DLlKkt6QcaakkcdYF0nQ9nKwkSqdSWGVvdTzUs3ia0cOjxiYaDJxYmPYmMa
            Gmtag0S3jrFpyoGD1KQvC3GGPH2tQkyxJXufTfKwFZUUXXg8vWrRF59CArocHRFU
            tuMDTbqQ6ubwkbYEW28jJCheu99HzBiyAVcda1+tu9O9nOgDIG91cQNamYo6DXL1
            SOiGrBrW2A6mjZrSAw+dZ7yzRNfm0v9QliOjh7HHT0DvgOpBCv9zu7+bmysOW8MX
            UKcaG6QW2UtS9UShAt/dWw63Bavobvob3iL4JC3y1MJPkwu8OKLalDMkuFCwmSQ5
            nNXFmromeeGKNmAGxuciX1SM2SbSAnP7hRaroIw7mGMdhL0Kig3kRz5EgcD40VHU
            ZgEJAhClLPspyoAjUu70Oh4LovQ9dqSZp+zvOtGbIgYORc74Dwlee5+1+xDcsri5
            Y0pEmjkByi85jNY3vbq5ZZpFkyNMOLPJMzo0tOIHzxB00ccxz9EDMkZx5K6TUwRM
            x2CqlXYACg==
            =u/Ck
            -----END PGP MESSAGE-----
          fp: F94F68B20C51D9B9C7EE4F7995AE41EF529CB276
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
