apiVersion: v1
kind: Secret
metadata:
    name: mattermost-db-credentials
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:oWT9ymj9n5LYnLd7F7PfE5YBLC3Rmn6okpupjK+y,iv:GvP+cJ+OotxAGsHiGIpL8pI0gAZkd/+KtiVMASo8Lnw=,tag:x6/2avVzfpVf1+6xaNZaCg==,type:str]
    username: ENC[AES256_GCM,data:dHvOshYaN9tGlw==,iv:EWlX/pDRpj5o/r4oRhs93lMw1wOfFd1VA3rDsIuZ524=,tag:dMPbP457Wl9SbQTPKQvdEw==,type:str]
    db_name: ENC[AES256_GCM,data:bWx4/V+n0isE/E8rzw==,iv:M9ST0xOTQra7dwfgGgY5WI6n5qp1+tV4sZTouEpwczQ=,tag:vLKw+kNM+ZzhxdIcn7ZDvA==,type:str]
    DB_CONNECTION_CHECK_URL: ENC[AES256_GCM,data:7+11U9PwTtuMSfU2wu6/4RTDXDs5Fadp2622aSFSJg8Uc42yEoGNBmTPz2R0mndNAXwKdXUfegimHpKvLYlDIdxbyH6KDDsaWbJwT6SjN1fKCVpmVtLbcUPZC6UxShPWS7iY1JrvhWaB2Z+zK1Xe5NhR+EJg23nIn9Ywd+VeBWViUi0+L6zqOwrDGGvp7FMj5BKRgg3DjbI6VYlafw==,iv:trfzLM+g0N/k0hPmdguJYThD1fR2Bka7Xu/dPhtSwLo=,tag:rUm72V3a17G39CjQD7LU7g==,type:str]
    DB_CONNECTION_STRING: ENC[AES256_GCM,data:7z1pNoRRKjEiYt8CNLURiGL8Vh77jnuMI9Jxbc12HZYz0I7pjqI27UzVfleq0cE7EcWc/1R4aebSbeRX8A5CaQAYGAr8uxvz7c5t6sthiXTPSERdoA+mGgNVEwnHi32wdbvBleJJd9CKQQ5pxb+6NLbMlJnl6JzK/FQQvm+kPCxtRBH914dnQm/1nDQK+sl34pXkNLN7pX1iUpVm1Q==,iv:/QIGXiA+ybVXtAoVXF689iEdz8lQxWAAgDeKrjF6MYM=,tag:ANI7KnfU9ut+PAmmfncrXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-21T20:26:21Z"
    mac: ENC[AES256_GCM,data:mAwoOvkC/ZJGv8NkbvNB8LpHw2chwjUyfcsYEZ4L2fNeMlTr3/UfsfKfBZWabiwMrp53G3Vq169HIjMDU4T7qCzCABCBK5LBGBXRtOHpSkd+DKS2sKunh1Z6gOAGjxeaitg1L7Nv3eKGPGOypQnzIS3PtUbVglS0U99lGC3h2jo=,iv:fV8xgx2zaoY+M2DF4NGPj2/X1JyD5ZbpCeU2HwL9k1k=,tag:3WDqy/Vbg/8EYLgoFaLzKw==,type:str]
    pgp:
        - created_at: "2025-04-21T20:26:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5O4Cu+lUBGNARAAkZGkeyRuI34SEKu4HWXW9NZEfmTAe3hBKUh8vok0CZv8
            ki+qKPyRcz3DmJB6L7pJDJwkUhRFdCILyfVRQLhC2etFLDg+Re3SPoDEKNqWEzY1
            +ObCblEmkrda74oyr5sOUma0ZIj9D6HVSmKh67Eqk08dSE14U6xik/J4SwQW11RE
            Ok1PCKaOsbHu0IRem2wUH3fM4TT4dppAoIxVkM4ARy0xMRzXO2OW7q1Vqe8P7fdc
            aSQnIjkWlM/mfkOX/uD9cYpS40tfrNutOcjiYC4z2qd4KxDgy5Ksav5wg1Pplas8
            3HFFmxYHEXlYdyf3rQa44vF6+tNOiz7SXOU8ME8fKq+Cw7wLYP2DWtrRpSO3k/7f
            IB4J9aX3k4tQlGZpPGx/Ut2HQgQkKMzKC/kwZ6FGQmX6AaytxL44sQpuVNvy4Nw4
            froCBEIPumLh5s/sRwOWf5CnlqPdVP5Xz7FQp2tPkX1qS4DPyfxD30hkKsG58yk2
            zIdWbaXV9pEu0Zgn7LvHdSS3Kvw6D1Og9JI1rUCgdBgvDTV369lk39JU5HEIQR+v
            CxyPTctLIlozbELkqvg7ZaM0GRv/92UGglJH97TroSi1X+Z/Wu78HfttTe6YUGa8
            DgVPa/OreKmX0QTthLw2n2+NrLeFQWmU195EMvG0LW75Sq2o/fedOJzMwNz2y6LU
            ZgEJAhBx37wTVAucQFXQYW0eyIYS5jTn5cdXvcgOpb+046G/k5b3u6MiZyvg+hpA
            6rjPQHg5rt71rqzEUMalCa9hI7u46bEkB+v1QWGBfGJZd5Dhas6SWgVOlCGJCcIU
            EOD3hE4eIA==
            =kaHM
            -----END PGP MESSAGE-----
          fp: F94F68B20C51D9B9C7EE4F7995AE41EF529CB276
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
