apiVersion: v1
kind: Secret
metadata:
    name: postgresql-credentials
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:aVy4ckhYevY=,iv:VMyRzfxjiZUmsLciNUMSKeWxvSRXCyCQp0sMx4bAOoE=,tag:07qi2dGoUIVyMphv5T0dYA==,type:str]
    username: ENC[AES256_GCM,data:7zXg1jYZWsQ=,iv:g/TThZdcdImhKE+SJoH2n7Y/pm/Jhve34uVFGvJkvWI=,tag:M3TO/RH+AzEnbebVi/6Q0w==,type:str]
    db_name: ENC[AES256_GCM,data:AgMXYicOFw==,iv:1SfNKI1fUWdVAKgwhcm03GBIu567+L8N/MeAhoDKxh0=,tag:pKPl5H9oPecbB6ajtPR54A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-21T18:17:20Z"
    mac: ENC[AES256_GCM,data:JO0WVwgUpk9td0A0xsvuWp1ioJI/Rn0JyKvO7CRNBSN19hGiZ5Y5josRk7qvr3LiwA3soC5vq962kj/c4wWaaoQ7hZVg226dgW29tY87Bmkk4k598Ezk8lSduzMFu9JWCWWow2p16nD8rlcnUG5L/sFdusSoC1laZX4Z14391pE=,iv:ck5z9Wn33hNcvRww97jTEw37n33DrMWMvMLmZzUghW4=,tag:TDn+zhItQgKWPcJ2c6esHw==,type:str]
    pgp:
        - created_at: "2025-04-21T18:17:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5O4Cu+lUBGNAQ//Y4QR7Cpd76sQ821T9D7hYdjCRWIVNge310cEGStPTE/a
            ajfj9+zFM8g9N/yE7B/JDMvPg2qY8CcHEGTr36+W5fbAAkLVPiz0PhoG1fa034Ty
            yFc4jVYlvmdPFYXXLPM6mthJ30UfNFhOahgcDrjpKkGRecWFSztLaFrjGZP9tLpT
            TDriG6Mjk9scYzk4xdjv3lMdVoFUNaccsS7MdnCy2x4S2Edr9/UorFG5TgjybanA
            wwowAWkXmNs1uFQRL3iIbjE/LOGZtZnKgxDQ85zBeyGlTxpREI8ZcoU9PAbzwvP7
            wkuPHuBxVJt6p7BuIDuD6iVj620ZQmy+NCAO8kIOs6rsNmnLtmeT0nGU8CDVHRtn
            wGA7sl4pGSDIQrushrWZYsV1xrM6rEjhpTfHEK+/nAybMsaSztaepLjR/wqfsJW9
            J9CgXdOR8F84n3zCJRyQe1zu/L867wB/MmIOOom7qn2Yp1WGmYddWTCmrT2ggNf2
            Mcvgl9l1+0KgzA04dtP1DtIOHYTCrKeX2NnWcrYT+i2WTHmvRU57Hd5J5+clpNru
            mLVTiu/1VJklF8wmp9TSJqF5XwlVMg6Qs5OZC6vRhziF3r/wA+K9wqXCFCPKk6La
            J+88Iebe7yAfbNecKsoc8oYODxkf/W1xTeeh7Ga2CbqxSY2u7TjpMQ06yyFBJAbU
            ZgEJAhD7vvEs9bpV7v53ZWgQx3n1uihO8++6ElJZru4pi7VBlqfqHb84mVRHE74p
            CvUNzzRDaJOX8buZqX7IuqqJkxWMWTRBiy4D3UMmc1MeJFBq51C//jG3DvXA4NnB
            0U8xDddP7g==
            =FtQD
            -----END PGP MESSAGE-----
          fp: F94F68B20C51D9B9C7EE4F7995AE41EF529CB276
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
