apiVersion: v1
kind: Secret
metadata:
    name: postgresql-credentials
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:IRgSQWB1WVY=,iv:825GUXqVY9Vbn5klKuU8fkCAE+9O8uAQ7Hme7m0yGjI=,tag:VJZMyAM/Edjiu/MiFYEA5g==,type:str]
    username: ENC[AES256_GCM,data:jGoTlw==,iv:W3XcSNpHLSYheQWlCz52eEkvojDo29wt2zw6wmgaS7k=,tag:hreXgpxSz2fWmAAztrfQLw==,type:str]
    db_name: ENC[AES256_GCM,data:ktw=,iv:nOg10QYx4lO3eheO2J1v3phts/fcBXOWi3O5Nbex7kU=,tag:3TvUg3z9nplctifRGW0zZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-21T18:03:50Z"
    mac: ENC[AES256_GCM,data:9VV7SLJ4+o7C4O8TumcmBN4Qjclf7wngridx6HZ7MKa0zNr0f+hoeZD8zZFBR4m/lgMNJGk/GwtOzBBvHwnNaG5HFsnDi8ciBVvFhzgiVwmXu1Saj/7XAD3JS2h/40hNXZv9+wdi6U8SMjw5YI8epZz+cFZGB2OgACZ/LnDxqSw=,iv:QpLZ4srk4VUPn1uWp4boBdplyMCqRi6IFlN3acrCSjg=,tag:96r/7DrkbNa/YQwV0vgTtg==,type:str]
    pgp:
        - created_at: "2025-04-21T18:03:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5O4Cu+lUBGNAQ//RQnD+CUUW+qRz+W3O0uZZpGk4xx88Cu8uyPj0Zwh62te
            T0gjZCZuayptlOovj3lbktsuwWj5jrBV0De5xZarzBBnIqsBa4GvD/JDxad9sQpo
            UgqhD+t/KpS8SI85TF/vC86bNdr3VaFJcE6yJrgz8PGiZsVyj4X5rJ3KgWJZQXrZ
            3fU3kPQKKQtHfOeaaQ3uiVgIfy6cFz98GJojvL6mByF2hOMsvr78Dq2DC9cqDvau
            YL2S2pPCmQktmAXghuCHj4FSW3SpQdEpG1y1FqGqNR+ckJiZSILV42l0A/5jdrAC
            f7eWwV3BP4KX/o4lcoqYN2mC9EEPFtmuSsRnayTRQzMEbefWv3unMLdJgmS2Qu/E
            vLURu55HiRE10FEc0COe8Fl26CogNmpKWRkoTTozJT5mRk36nnhaxRXD4b6WylcL
            s050lUUl2pp6maGFm/F2RUjYM6+mPIU3KFWc09kpsjeAM7UdvhLTWQbvS5gP210f
            HjJ/6ep2EJHjc+vTWpWT+yXM+GyFV3m1kiEjXpLlWfVksGuJJZ0L+47+Hstyk9FS
            fWcLWayuGiJsanjV6szY8uTzigeGyKjVWTFoyPgQIMHkLcOMm6nRUSBP7XzgOb/+
            Lk+ndVB/8abMSxWKb+oUsCyzCMap4cXAZmcmVtoiUxVNP4E1HUWZVbWdmXslne3U
            aAEJAhA3VTDWOK5EhGjfyp5RQ4SNSxEDRQpi9cuokwvMzrFcX2GVBFvcKE1R44OU
            CbsrCCgXCvheewntqKfizFG96PMu6cbAteUMIjOudKgQTJ6n83HEhj3VrBP+7Rnq
            EN4ucpuhxmYe
            =ivk0
            -----END PGP MESSAGE-----
          fp: F94F68B20C51D9B9C7EE4F7995AE41EF529CB276
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
