kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mattermost-postgresql-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: mattermost-postgresql-pv
  storageClassName: ""