apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: samba
  name: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
      - image: philgman1121/samba-amd:1.0
        name: samba
        env:
          - name: USER
            valueFrom:
              secretKeyRef:
                name: smb-credentials
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: smb-credentials
                key: password
        ports: 
          - containerPort: 139
            name: smb-139
          - containerPort: 445
            name: smb-445
        volumeMounts:
          - name: samba-persistent-storage
            mountPath: /nas-vol
      volumes:
        - name: samba-persistent-storage
          persistentVolumeClaim:
            claimName: samba-claim