apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: samba

generatorOptions:
  disableNameSuffixHash: true

resources:
  - smbcredentials.enc.yaml
  - namespace.yaml
  - storageClass.yaml
  - persistentVolume.yaml
  - persistentVolumeClaim.yaml
  - deployment.yaml
  - service.yaml
