apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: samba

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - storageClass.yaml
  - persistentVolume.yaml
  - persistentVolumeClaim.yaml
  - deployment.yaml
  - service.yaml

generators:
  - secret-generator.yaml
  # - test1.yaml
