kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: samba-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: samba-samba-pv
  storageClassName: ""