apiVersion: v1
kind: PersistentVolume
metadata:
  name: samba-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # storageClassName: my-local-storage
  local:
    path: /volumes/ssd-1/nas-vol
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: disk
  #           operator: In
  #           values:
  #           - disk1  