apiVersion: v1
kind: Secret
metadata:
    name: smb-credentials
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:8e/UMQ==,iv:4Ti8koK6b12GvLVtTFTqNqhW28T6lnMFvPoKJ5n6S8g=,tag:SoKPJMAhd+f163xEDcq+Ow==,type:str]
    password: ENC[AES256_GCM,data:LfqIfjsEZh6Oob6K3zPgT9o=,iv:Xs84YE38vfW26hAh7ps/em/B1kfPOu7nczi3IgGzG2M=,tag:PwcKyy2Fu0NPM85oz3bWCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-04T03:42:39Z"
    mac: ENC[AES256_GCM,data:z0TUTX0zQt8A8jlNl9hXWgn9APYJZbkgaLZ1D3GwGv4LclRBU7FP/o+oQJKTXOGAX72szsFn8rm/nMkhsMHvxNly/JxtYXcsjyPpyPwB2CHblaJWT+baEXIb40sXH7UCq9COfloYzrgY23EAaCNfDvE0/ACDtUsbBYYwVd/sgRo=,iv:QKhvA0pj+6ziVu1dvHQDJV2GryY30AcJYtHvGl8FYtY=,tag:/ZmNKOD0DNFzPIlE0b85Vg==,type:str]
    pgp:
        - created_at: "2023-02-04T03:42:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5O4Cu+lUBGNAQ/+NtINXl+MGDNK8hTNQOUZR8i8C+WhsufMkgMVOi2NLc4m
            RnQLdsc1wWO2GJjGsvhqBUBUJe5EJGd471JZLqC6aN5ZdFyUrtu18o+GgAqcWCeV
            6naQz87+gQ2EWQm6TaKLsbaDbNkxjgXZLBKiy6w3vqD3SLjHzVBZuWnCk20o4vYv
            VYwHqBDYWY2m5HowiIGyhErnP+9vZGjx4SsEr+JGxRqTp8fkgLq6JijyHqyp6lyC
            qMYnMs5DWPS9prVekkMVR/K2E+pdqOq37Nej4pfD50ySz+bYXy10ZWs+n51+IUUe
            bROMV2e+F4MNNrbp0QVNU7Cvse3K8ID3cJkSRXU0FtplCMR8Jsk758kuM0iEHgLK
            8mwNZSYueNmziYdNlj2DmmuIFV1ixS0kaTNr0QBKvt1Gfa7dmFxA/aNKRqD/TI8e
            M1w3xkWTPoaIfGfE24H6A3K86+VOOFhm8hP/5phdI5+5kTpRd05S2q01nZGsHx3D
            YfYhm5wbdpp03iDxNlt2tSTPK6p9+S0TljaTvHgblJP8nRK2VwKtlJi4aeToVxeC
            x6kZG3pgeW5Qws32dWpVIZo8x3njn+OTiVe9RX2Sph9qT25Z3wFMZUUabslHhnjC
            G6CGQxp5vjJUzTnCE4rVyEiRdQj0IxswhWnzS3kjm7fcfUZ3AgLXtB17crx1FcPU
            aAEJAhBLOoWlhkbUjStggiATFtWJ/afd1NWGps3pFPuIqNpvBCty3nU93tlCsr8I
            hJahMqCx3guACuGhh52Z2whe+bP92WRnQrQJrueWpxzN+aQP0/kjG5fOcVCF/447
            8IYOEte/hrY9
            =YZKs
            -----END PGP MESSAGE-----
          fp: F94F68B20C51D9B9C7EE4F7995AE41EF529CB276
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
