apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: ENC[AES256_GCM,data:+ypaRvbi1z0=,iv:BgiZRVo4/qKomP6TZuTWUOzjK0Hb0vMT2mpojq1sXso=,tag:JcV24bdhRsZaLC9BXPoJzw==,type:str]
    password: ENC[AES256_GCM,data:/RGahMWAtaKi6dwFAEKNRA==,iv:ZmQ/LbmhiARyoyBcBOy1Ap2GHr4C5cF5KUWAmAcIrpE=,tag:Gw7DA8zJZdfzhvpR0zSvRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-01T19:50:52Z"
    mac: ENC[AES256_GCM,data:6fFCOmiuv2BYP6exfo+FFs6dguknjWXbL11Xgim0XP5eKGaN/jntMzw3vab+TwtN9+OExCqHrKyDLXO+RHGXYF3eeHWbKX9TM5LjNPkhHEOiAIFJW/ELhi9rcWYgmffSA8lN4j7AV/Cbxs8fjEVpdPcgokqdUO4H+wZwAfEViAk=,iv:NYCGnnYA+0c9OYcOM8VExuKgAPhFoZmkoUnO4+Mi/xI=,tag:fy9ZXR63yG5i4Wil7raifw==,type:str]
    pgp:
        - created_at: "2023-02-01T19:50:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA13jbxIEUYaBAQ/9GLum2MBmo/Ol3jsZo/W12lyp3Fok+yP2dtQop9SGDxkF
            SRa2zek2YDaar2EgPR/lGOGc+bpcM2CRCwJoIrWs27w8eZEbsiVUT/JdVqjzyLSg
            +5Ti2aF0uRUnlfe/RIaMkB0SrfmooP8Slolox5hE2e4fD3qK9vCNq+VuxGlw6iyc
            +Oyrj0wnCUFB3F7SFfWh2tk7oLWJAO7dG45XrrIAcsk5KOkvODtikfx32mgjc4Mw
            RJ9WmlNqBW+WK0+nnKJ+rvD0GK5a/SyWRma0pYqQL6MWEKfYhCuiFG5rkPtYP3VC
            neZzqU8D5aHePQNgxU0XDI85pCwud9CaId/pDD5IJhbj3g17SGJHdsn6DiXDKFNr
            WCOCw0eusyWstdjGuaixu5bA3v1jexfxQBRmbCOJzwTDs7FiJbjAo9x2qMumyUQU
            m5PmSFYf5IDPV/4J4okiqy9XHoNTidzgRqaV2tXT/jOBFINnPTEwSIW5yXMGDDBH
            OYrd5NbJJE0n3nT47vyJqqHsCJduVKm+BvO2dkthsoWigSPwqPCR4SZaZiUZ5L+u
            cvsW+gGYmx7Pd596LRGWkkH5ZvQp24PgOhRsHonEMebSgBZxwXNtQ/WE2JV+uyB2
            T3rJXwMCyI7fv7IQb1U+LGZz0kve50V1Or0gv2TN13EfuJG57CZ5MYkp0XLfUwjU
            aAEJAhBVdDJP9wBCrENEKJl4TRtmxpBS2mr5jJU7Zb6jviW+gmtqosdxWXhIw+5g
            /wc19KFkzVaM/nbbGDkUyK3gJQUA61A5b3J2QTjcHMRBEB7EP+k8aWl5YefGY70A
            qgg2isDjKD+g
            =r63L
            -----END PGP MESSAGE-----
          fp: A895CF23FF129E6BA20E2871CCAE56820A470E76
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
